### ISSUE TITLE
file_handler.runtime() outputs a lot of text

### ISSUE THREAD

**Issue by Siggenx** [copperwire/cephalopod#2]
file_handler.runtime() outputs all the information, I can suppress it by using ; after the function call, but just thought you should know.

**Comment by copperwire** [comment]
Does this occur when you're running the file chooser from a python file? i.e a file test.py that calls upon  the runtime function? 

It does not exhibit this behavior on my end other than when the function is executed in a terminal environment. 

In any case I've added a semicolon to the offending call in the runtime function and it seems to be functioning properly.
